package uk.co.stikman.euler.p2;

import uk.co.stikman.euler.base.ProblemBase;

public class P2 extends ProblemBase {

	public static void main(String[] args) {
		System.out.println(new P2().run());
	}

	/**
	 * Each new term in the Fibonacci sequence is generated by adding the
	 * previous two terms. By starting with 1 and 2, the first 10 terms will be:
	 * 
	 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	 * 
	 * By considering the terms in the Fibonacci sequence whose values do not
	 * exceed four million, find the sum of the even-valued terms.
	 */
	@Override
	public String run() {
		long tot = 0;
		long i = 1;
		long i0 = 1;
		long i1 = 1;
		while (i <= 4000000) {
			i = i0 + i1;
			i0 = i1;
			i1 = i;
			if (i % 2 == 0)
				tot += i;
		}
		return Long.toString(tot);
	}

	@Override
	public String getName() {
		return "Even Fibonacci numbers";
	}

}
