package uk.co.stikman.euler.problems;

import uk.co.stikman.euler.base.ProblemBase;

public class P45 extends ProblemBase {

	public static void main(String[] args) {
		System.out.println(new P45().run());
	}

	/**
	 * <pre>
	 * Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
	 * 
	 * Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
	 * Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
	 * Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
	 * It can be verified that T285 = P165 = H143 = 40755.
	 * 
	 * Find the next triangle number that is also pentagonal and hexagonal.
	 * </pre>
	 */
	@Override
	public String run() {
		int t = 285;
		int p = 165;
		int h = 143;
		while (true) {
			long nt = fT(++t);
			long np;
			long nh;
			while ((np = fP(p)) < nt)
				np = fP(++p);
			while ((nh = fH(h)) < nt)
				nh = fH(++h);
			if (nt == nh && nt == np)
				return Long.toString(nt);
		}
	}

	private static long fT(long n) {
		return n * (n + 1) / 2;
	}

	private static long fP(long n) {
		return n * (3 * n - 1) / 2;
	}

	private static long fH(long n) {
		return n * (2 * n - 1);
	}

	@Override
	public String getName() {
		return "Triangular, pentagonal, and hexagonal";
	}

}
